blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/codebar-ag/laravel-zendesk/issues/new
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/codebar-ag/laravel-zendesk/issues/new
    about: Share ideas for new features
  - name: Report a bug
    url: https://github.com/codebar-ag/laravel-zendesk/issues/new
    about: Report a reproducable bug
