<?php

namespace CodebarAg\Bexio;

use CodebarAg\Bexio\Contracts\BexioOAuthAuthenticationStoreResolver;
use CodebarAg\Bexio\Contracts\BexioOAuthAuthenticationValidateResolver;
use CodebarAg\Bexio\Contracts\BexioOAuthConfigResolver;
use CodebarAg\Bexio\Support\DefaultBexioOAuthAuthenticationStoreResolver;
use CodebarAg\Bexio\Support\DefaultBexioOAuthAuthenticationValidateResolver;
use CodebarAg\Bexio\Support\DefaultBexioOAuthConfigResolver;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class BexioServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
            ->name('laravel-bexio')
            ->hasConfigFile('bexio')
            ->hasRoute('bexio');
    }

    public function registeringPackage(): void
    {
        $this->app->bind(BexioOAuthConfigResolver::class, DefaultBexioOAuthConfigResolver::class);
        $this->app->bind(BexioOAuthAuthenticationStoreResolver::class, DefaultBexioOAuthAuthenticationStoreResolver::class);
        $this->app->bind(BexioOAuthAuthenticationValidateResolver::class, DefaultBexioOAuthAuthenticationValidateResolver::class);
    }

    public function bootingPackage(): void
    {
        parent::bootingPackage(); // TODO: Change the autogenerated stub

        // Issue Temporary Fix:
        // https://github.com/spatie/laravel-data/pull/699#issuecomment-1995546874
        // https://github.com/spatie/laravel-data/issues/731
        config()->set('data.throw_when_max_transformation_depth_reached', true);
    }
}
