<?php

namespace CodebarAg\Bexio;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class BexioServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
            ->name('laravel-bexio')
            ->hasConfigFile('bexio')
            ->hasRoute('bexio')
            ->hasViews('bexio');
    }

    public function bootingPackage()
    {
        parent::bootingPackage(); // TODO: Change the autogenerated stub

        // Issue Temporary Fix:
        // https://github.com/spatie/laravel-data/pull/699#issuecomment-1995546874
        // https://github.com/spatie/laravel-data/issues/731
        config()->set('data.throw_when_max_transformation_depth_reached', true);
    }
}
